var caffeine_drinks = [
  "1 oz Pure Liquid Caffeine",
  "10 Hour Energy Shot",
  "28 Black Energy Drink",
  "4C Energy Liquid Water Enhancers",
  "4C Energy Rush",
  "5 Alarm Energy Shot",
  "5 Hour Energy",
  "5 Hour Energy Decaf",
  "50 Cal Energy Shot",
  "6 Hour Power",
  "7-Eleven Energy Shot",
  "7-Up",
  "A&W Cream Soda",
  "A&W Root Beer",
  "ABB Diet Turbo",
  "Ace Energy Drink",
  "Active Brain Energy Shot",
  "Acute Fruit Energy Drink",
  "Afri Cola",
  "Ale 8 1",
  "ALRI Hypershot",
  "Americano Coffee",
  "Ammo Energy Shot",
  "Amp Energy Drink",
  "Arby's Jamocha Shake",
  "Archer Farms Energy Drink",
  "Arizona Arnold Palmer Half and Half",
  "Arizona Caution Energy Drink",
  "AriZona Extreme Energy Shot",
  "Arizona Iced Tea",
  "Arriba Horchata Energy",
  "Atomic Blast",
  "Avitae Caffeinated Water",
  "AZ Energy Drink",
  "B 63 Energy Drink",
  "BANG Energy Drink",
  "Barq's Red Creme Soda",
  "Barq's Root Beer",
  "Baskin Robbins Cappuccino Blast",
  "Battery Energy Drink",
  "Battery Juiced Energy Drink",
  "Bawls",
  "Bawls Cherry",
  "Bawls Exxtra",
  "Bawls Geek Beer",
  "Bazi Energy Drink",
  "Bean and Body Coffee",
  "Beaver Buzz Energy Drink",
  "Berocca",
  "Big Jak Energy Drink",
  "Big Red Soda",
  "Big Train Java Chip Ice Coffee",
  "Big Train Spiced Chai",
  "Biggby Brewed Coffee",
  "Biggby Creamy Lattes",
  "Biggby Espresso",
  "Biggby Frozen Lattes",
  "Biggby Iced Coffee",
  "Biggby Iced Tea",
  "Bing Energy Drink",
  "Blade Energy Drink",
  "Blink Energy Water",
  "Blood Energy Potion",
  "BLU Energy Drinks",
  "Blu Frog Energy Drink",
  "Blue Bolt",
  "Blue Charge",
  "Blue Energy Drink",
  "Blutonium Energy Drink",
  "Bomba Energy Drink",
  "Boost Energy Drink",
  "Boost Nutritional Drink",
  "Booty Sweat Energy Drink",
  "Brain TonIQ",
  "Brawndo Energy Drink",
  "Brown Rice Tea",
  "Bulldog Buzz",
  "Bulletproof Coffee",
  "Burn Energy Drink",
  "Buzz Monkey",
  "BuzzWater",
  "Cafe Viva Probiotic Coffee",
  "Caffe Mocha",
  "Caffe Nero Coffee",
  "Caffeinated Club Soda",
  "Caffeine Energy Drink",
  "Canada Dry Green Tea Ginger Ale",
  "Canadian Big Buzz Green Machine Energy",
  "Cannabis Energy Drink",
  "Cappuccino",
  "Caribou Brewed Coffee",
  "Celsius Energy Drink",
  "Chameleon Cold Brew Coffee",
  "CHARGE! Super Shot",
  "Cheerwine",
  "Cheetah Power Surge",
  "Cherry Coke",
  "Chocolate Milk",
  "Choffy (roasted cacao)",
  "Cintron Energy Drink",
  "Clif Shot Turbo Energy Gel",
  "Club Mate",
  "Coca-Cola C2",
  "Coca-Cola caffeine free",
  "Coca-Cola Classic",
  "Coca-Cola Zero",
  "Cocaine Energy Drink",
  "Cocaine Energy Shot",
  "Coffee (Brewed)",
  "Coffee (Decaf, Brewed)",
  "Coffee (Decaf, Instant)",
  "Coffee (Espresso)",
  "Coffee (Instant)",
  "Coffee Bean & Tea leaf Coffee",
  "Cojones Energy Shot",
  "Coke Zero",
  "CoMotion",
  "Costa Coffee",
  "Cougar Energy Double Shot",
  "Cranenergy Juice",
  "Crave Energy Drink",
  "Crunk Energy Drink",
  "Crystal Light Energy",
  "Crystal Light Focus",
  "Crystal Light Iced Tea",
  "Cult Cola",
  "Cyborg",
  "Dark Dog Energy Drink",
  "Death Wish Coffee",
  "Demon Energy Drink",
  "Demon Energy Shot",
  "Deton8 Powdered Drink Mix",
  "Diablo Energy Drink",
  "Diabolo Loco Energy Drink",
  "Diet A&W Cream Soda",
  "Diet Cheerwine",
  "Diet Cherry Coca-Cola",
  "Diet Coke",
  "Diet Coke Plus",
  "Diet Coke with Lemon",
  "Diet Coke with Lime",
  "Diet Coke with Splenda",
  "Diet Dr Pepper",
  "Diet Dr Pepper Cherry",
  "Diet Dr Pepper Cherry Vanilla",
  "Diet Mountain Dew",
  "Diet Mr. Pibb",
  "Diet Pepsi",
  "Diet Pepsi UK",
  "Diet RC Cola",
  "Diet Ruby Red Squirt",
  "Diet Sunkist Orange Soda",
  "Diet Turbo Tea",
  "Diet Vanilla Coke",
  "Diet Wild Cherry Pepsi",
  "Divas Energy Drink",
  "DNA Energy Drink",
  "DOC 360",
  "Dominator Black Energy Drink",
  "Dominator Energy Drink",
  "Don Tomas Estate Coffee",
  "Double Cola",
  "Dr Pepper",
  "Dr Pepper 10",
  "Dr Pepper Cherry",
  "Dr Pepper Cherry Vanilla",
  "Dragon Pearl",
  "Duff Energy Drink",
  "Dunkin' Donuts Brewed Coffee",
  "Dutch Bros. Blue Rebel Energy Drink",
  "Dutch Bros. Coffee",
  "DynaPep",
  "E6 Energy Shot",
  "Eboost Energy Drink",
  "ED Energy Drink",
  "Einstein Bros Coffee",
  "Element Caffeinated Water",
  "Emerge",
  "EnerBee Energy Drink",
  "Energi-ZING Shake by Nutrisystem",
  "Energy Catalyst",
  "Enerji Green Tea Energy Shot",
  "Enorm Energy Drink",
  "Epiphany Energy Drink",
  "Eruption Effervescent Energy",
  "Eternal Energy Shot",
  "Ex Energy Drink",
  "Extra Water Energy Drink",
  "Extreme Thermo Rush",
  "Facedrink Energy Shot",
  "Fakeer Energy Drink",
  "Fanta",
  "Fast Lane Black Tea",
  "Faygo Cola",
  "Faygo Moon Mist",
  "Fein Energy Crystals",
  "Fighter Energy Drink",
  "Fire Blade Energy Drink",
  "Flat White",
  "Flatt Cola",
  "Flying Power Energy Drink",
  "FMF Power Energy Drink",
  "Frava Caffeinated Juice",
  "Fresca",
  "Freshe Energy Drink",
  "Fritz Kola",
  "FRS Energy Drink",
  "Fuel Cell",
  "Fuel Energy Drink",
  "Full Throttle Energy Drink",
  "Full Throttle Frozen Blast",
  "Function Alternative Energy",
  "Fuze Iced Tea",
  "G Fuel Energy Drink Mix",
  "G Pure Energy Drink",
  "G Shot Antioxidant Energy",
  "GaGa Energy Drink",
  "Game Juice",
  "Ginger Ale",
  "Gloria Jean's Coffee",
  "Go Fast Energy Drink",
  "Go Fast! Coconut",
  "Go Girl Energy Drink",
  "Go Loco- Loco Tonic",
  "Golazo Sports Energy Drink",
  "Grazzhopper Energy Drink",
  "Great Value Energy Drink Enhancers",
  "Great Value Energy Drink Mix",
  "Greek Coffee (Metros)",
  "Green Go",
  "Guayaki Canned Yerba Mate",
  "Guayaki Energy Shots",
  "Guayaki Yerba Mate Bottled Tea",
  "Guayusa Tea",
  "Guru Energy Drink",
  "Hansen's Diet Red",
  "Hansen's Energy Pro",
  "Hardcore Energize Bullet",
  "Havoc Energy Drink",
  "Hawaiian OLA Noni Energy Shot",
  "Health Energy Potion",
  "Helix Energy Drink",
  "Hershey's Chocolate Milk",
  "Hi Ball Energy Drink",
  "High Brew Coffee",
  "Hijinks Energy Mixer",
  "Honest Professor Fizz",
  "Honest Tea",
  "Hot Cocoa",
  "Hot Pure Energy Drink",
  "Howling Monkey Energy Drink",
  "Hydrive Energy Water",
  "Hydrive Extra Power",
  "Hydroxycut Instant Shot",
  "Hype Energy Drink",
  "IBC Root Beer",
  "Illy Issimo Latte Macchiato",
  "Inca Kola",
  "Indigo Energy Drink",
  "Ink",
  "Inko's White Tea Energy",
  "Irn Bru 32",
  "Ironclad Energy Drink",
  "iShot Energy Shot",
  "iShot Love Potion",
  "iShot Skinny Energy Shot",
  "Jamba Juice Energy Drink",
  "Java Chai",
  "Java Monster",
  "Jazz Caramel Cream",
  "Jolt Endurance Shot",
  "Jolt Energy Drink",
  "Jump Start Energy Drink",
  "K-Cup Coffee",
  "Karvana Kombucha Energy Shot",
  "Keurig Vue Pack",
  "Kick Energy Drink",
  "Kill Cliff Recovery Drink",
  "Killer Buzz",
  "King 888 Energy Drink",
  "Kinley Soda",
  "Kirkland Energy Shot",
  "Knockout Energy Drink",
  "Kombucha Extreme Energy Shot",
  "Kombucha Tea",
  "Kona Red",
  "KX Energy Drink",
  "Latte",
  "Life Blast Xtreme Energy",
  "Lift Off Energy Drink",
  "Lift Plus Energy Drink",
  "Limelite Fusion Energy Drink",
  "Lipton Brisk Green Tea",
  "Lipton Brisk lemon",
  "Lipton Iced Tea",
  "Lipton Natural Energy Tea",
  "Lipton Tea",
  "Liquid Ice Energy Drink",
  "Liquid Lightning",
  "Liquid Ninja Energy Drink",
  "Liquid Z Juiced Energy Drink",
  "Long Black",
  "Lost Energy Drink",
  "Lucozade",
  "Lyft Energy Stick",
  "M-150 Energy Drink",
  "Mad Croc Energy Drink",
  "Mamma Chia Energy",
  "Mana Energy Potion",
  "Mario Power Up Energy Drink",
  "Matcha Tea",
  "Max Velocity Energy Drink",
  "McDonalds Coffee",
  "McDonalds Iced Coffee",
  "McDonalds Sweet Tea",
  "Mega Monster Energy Drink",
  "Mello Yello",
  "Mello Yello Zero",
  "MiO Energy Water Enhancer",
  "Missile Energy Drink",
  "Mix and Go",
  "MonaVie",
  "Monster Absolutely Zero",
  "Monster Assault",
  "Monster Cuba Lima",
  "Monster Energy Drink",
  "Monster Export",
  "Monster Extra Strength",
  "Monster Hitman Sniper",
  "Monster Import",
  "Monster Khaos",
  "Monster Lo-Carb",
  "Monster M3 Energy Drink",
  "Monster Mixxd Energy Drink",
  "Monster Rehab Energy Drink",
  "Monster Ripper",
  "Monster Ultra Blue Energy Drink",
  "Monster Ultra Pink Energy Drink",
  "Monster Zero Ultra",
  "Morning Spark Energy Drink",
  "Morning Thunder Tea",
  "Mother Energy Drink",
  "Mother Inferno",
  "Mountain Dew",
  "Mountain Dew Baja Blast",
  "Mountain Dew Code Red",
  "Mountain Dew Game Fuel",
  "Mountain Dew Kick Start",
  "Mountain Dew Live Wire",
  "Mountain Dew Voltage",
  "Moxie Energy Drink",
  "Mug Root Beer",
  "Muscle Monster",
  "Naked Juice Energy Smoothie",
  "Nap Nock Energy Shot",
  "Nawgan Energy Drink",
  "NEO Energy Drink",
  "Neon Energy Drink",
  "Nerd Energy Drink",
  "Nescafe Ice Java",
  "Nescafe' Ricoffy",
  "Nespresso Coffee Capsules",
  "Nestea Iced Tea",
  "Nestle Milo",
  "Neuro Sonic",
  "Neurofuel Energy Drink",
  "Neutron Energy Drink",
  "Nexcite Energy Drink",
  "No Fear Energy Drink",
  "NoDoz Energy Shot",
  "NOS Active Sports Drink",
  "NOS Energy Drink",
  "NOS Energy Drink (New Zealand Brand)",
  "NOS Energy Shot",
  "NOS Loaded Cherry",
  "O Infused Water - Energize",
  "Octane Energy Burst",
  "Octane Energy Drink",
  "Oi Ocha Green Tea",
  "OK Energy Drink",
  "Ol' Glory Energy Drink",
  "ON Energy Drink",
  "OnGo Energy Shot",
  "OnTheGo Drink Mix",
  "Oprah Chai Tea Latte",
  "Orange Crush",
  "Oregon Chai Tea",
  "Ovaltine",
  "Pacific Chai",
  "Peace Tea",
  "Peet's Brewed Coffee",
  "Peet's Coffee Espresso",
  "Peet's Decaf Espresso",
  "PepPod Energy Drink",
  "Pepsi Caffeine Free",
  "Pepsi Cola",
  "Pepsi Cola UK",
  "Pepsi Diet Lemon",
  "Pepsi Diet Lime",
  "Pepsi Diet Vanilla",
  "Pepsi Max",
  "Pepsi Max UK",
  "Pepsi Next",
  "Pepsi One",
  "Pepsi Slurpee",
  "Pepsi Throwback",
  "Phix Energy Drink",
  "Pibb Xtra",
  "Pibb Zero",
  "Pirate Energy Shot",
  "Plasma Energy Drink",
  "Player Aid Energy Shot",
  "Please Energy Drink",
  "Positive Energy Juice",
  "Potencia Energy Drink",
  "Power Edge Energy Drink Mix",
  "Power Horse Energy Drink",
  "Power Trip Energy Drink",
  "Powerade Fuel +",
  "Powerthirst Energy Drink",
  "Premium Cola",
  "Pronto Coffee",
  "Propel Zero Energy Mix",
  "Pulse",
  "Pure Cofain 699",
  "Pure Kick Energy Drink",
  "Pure KYK Energy",
  "Pure Leaf Iced Tea",
  "Pyure o.e.o. Energy Shot",
  "Quad Energy Drink",
  "Race Energy Drink",
  "Radioactive Energy Drink",
  "Rage Inferno",
  "Rage Liquid Energy",
  "Ram Jam Energy Drink",
  "RC Cola",
  "RC Cola, Cherry",
  "Real Beanz Iced Coffee",
  "Realife Plus Energy",
  "Reckless Energy Shot",
  "Red Bull",
  "Red Bull Total Zero",
  "Red Devil Energy Drink",
  "Red Eye Energy Drink",
  "Red Fin Energy Shot",
  "Red Flash",
  "Red Heel Drink",
  "Red Rain Energy Drink",
  "Red Rock Cola",
  "Red Rooster",
  "Red Rose Energy Tea",
  "Red Thunder Energy Drink",
  "Red Thunder Energy Shot",
  "Redline Energy Drink",
  "Redline Power Rush",
  "Redline Princess",
  "Redline Xtreme Shot",
  "Reeds Energy Elixir",
  "Relentless Energy Drink",
  "Rip It Energy Drink",
  "Rip It Energy Shot",
  "Ripped Force Energy Drink",
  "Ritz Cola",
  "Rize Energy Drink",
  "Roaring Lion Energy Drink",
  "Robust Energy Drink",
  "Robusta Coffee",
  "Rock On Energy Shot",
  "Rockstar",
  "Rockstar (NZ / Aus)",
  "Rockstar Energy Cola",
  "Rockstar Energy Shot",
  "Rockstar Energy Water",
  "Rockstar Iced Energy Drink",
  "Rockstar Juiced",
  "Rockstar Perfect Berry",
  "Rockstar Punched",
  "Rockstar Punched (non-USA)",
  "Rockstar Punched Guava",
  "Rockstar Pure Zero Energy Drink",
  "Rockstar Recovery",
  "Rockstar Roasted",
  "Rockstar Sparkling Energy",
  "Rockstar Super Sours",
  "Rockstar XDurance Energy Drink",
  "Rockstar Zero Carb",
  "RootJack Caffeinated Pirate Root Beer",
  "Ruby Red Squirt",
  "Rude Energy Drink",
  "Rumba Energy Juice",
  "Runa Clean Energy Drink",
  "Rush! Energy",
  "Sambazon Amazon Energy Drink",
  "Sarsaparilla",
  "Scheckters Organic Energy Drink",
  "Screamin Energy Max Hit",
  "Seattle's Best Brewed Coffee",
  "Sencha Green Tea Shot",
  "Sex Drive Energy Drink",
  "Shark Energy Drink",
  "Shasta Cola",
  "Shock Coffee Triple Latte",
  "Sin Energy Drink",
  "Ski Soda",
  "Slam Energy Drink",
  "Slammers Energy Drink",
  "SLAP Energy Drink",
  "Slim-Fast Cappuccino Delight Shake",
  "Slurpee, Cherry",
  "Slurpee, Crystal Light",
  "Snapple Tea",
  "SoBe Energy Citrus",
  "SoBe Green Tea",
  "SoBe Power Fruit Punch",
  "Soda Stream",
  "Source Energy Drink",
  "Southern Sweet Tea",
  "Spark Energy Drink",
  "Spartan Energy Drink",
  "Speed Energy Drink",
  "Speed Stack Energy Drink",
  "Spider Energy Drink",
  "Spike Energy Double Shot",
  "Spike Energy Drink",
  "SPIKE Shooter",
  "Sport Max Energy Shot",
  "Sprite",
  "Stakk'd Caffeine Mixer",
  "Starbucks Bottled Frappucino",
  "Starbucks Bottled Iced Coffee",
  "Starbucks Decaf Coffee",
  "Starbucks Discoveries Caffe Mocha",
  "Starbucks Double Shot",
  "Starbucks Doubleshot Energy + Coffee",
  "Starbucks Grande Caffe Americano",
  "Starbucks Grande Caffe Latte",
  "Starbucks Grande Caffe Mocha",
  "Starbucks Grande Cappuccino",
  "Starbucks Grande Coffee",
  "Starbucks Iced Espresso",
  "Starbucks Refreshers",
  "Starbucks Refreshers Canned",
  "Starbucks Verismo Coffee Pods",
  "Starbucks Via Ready Brew",
  "Steaz Organic Energy Drink",
  "Stewie's Mind Erase Elixir",
  "Stok Black Coffee Shots",
  "Street King Energy Shot",
  "Sun Drop",
  "Sunkist Orange Soda",
  "Sunkist Solar Fusion",
  "Sunkist Sparkling Lemonade",
  "Sunkist Ten",
  "SunnyD X Energy Drink",
  "Surge Energy Shot",
  "Swing Juice Energy Drink",
  "Swiss Miss Mocha Cappuccino",
  "Swiss Miss Pick-Me-Up",
  "T-Virus Antidote",
  "TaB",
  "Taiwanese Milk Tea",
  "Talon Energy Drink",
  "TAPOUT Energy Drink",
  "Tazo Chai",
  "Tea (Black)",
  "Tea (Decaf)",
  "Tea (Green)",
  "Tea (Herbal)",
  "Tea (Iced)",
  "Tea (Instant)",
  "Tea (Jasmine)",
  "Tea (Oolong)",
  "Tea (White)",
  "Teas' Tea Oolong",
  "TEHO Energy Drink",
  "Tejava Iced Tea",
  "Tiger Energy Drink",
  "Tim Hortons Large Brewed Coffee",
  "Tim Hortons Small English Toffee Coffee",
  "Tim Hortons Small French Vanilla Coffee",
  "TK Diet Cola",
  "Tonic Water",
  "Tonix Energy Soda",
  "Topplez Cafe 125",
  "Trader Joe's Energy Drink",
  "Trim Water",
  "TroopFuel Energy Drink",
  "Tropicana Twister Soda",
  "Tru Blood Energy Drink",
  "Turkey Hill Iced Tea",
  "Twig Tea (Kukicha)",
  "Ubermonster Energy Brew",
  "UPTIME Energy Drink",
  "USANA Rev3 Energy Drink",
  "V Energy Drink",
  "V Pocket Rocket Energy Shot",
  "V8 Fusion Energy Drink",
  "Vamp Energy Drink",
  "Vanilla Coke",
  "Vegas Fuel Energy Drink",
  "Venom Black Mamba",
  "Venom Death Adder",
  "Venom Mojave Rattler",
  "Vernors Ginger Ale",
  "Verve! Energy Drink",
  "Vidration Enhanced Water",
  "Viso Energy Drink",
  "Vita Coco Cafe",
  "Vital 4U Liquid Energy",
  "Vital Energy Drink",
  "VitaminWater Energy Drink",
  "VitaRain Energy Enhanced Water",
  "Vixen Energy Drink",
  "Voltz 5 Hour Energy Shot",
  "Vuka Functional Drinks",
  "Warrior Energy Drink",
  "Water Joe",
  "Whey Up Energy Drink",
  "White Tiger",
  "Whoop Ass Energy Drink",
  "Wicked Energy Drink",
  "Wicked Hammer Energy",
  "Wild Cherry Pepsi",
  "Winrgy Energy Drink",
  "Wired X 3000 Energy Drink",
  "Wired X Berry Rush",
  "Wired X344 Energy Drink",
  "Worx Energy Shot",
  "X Ray Energy Drink",
  "XAPP Protein Energy Drink",
  "Xingtea Flavored Tea",
  "Xingtea Green Tea Energy",
  "Xingtea Just Plain Tea",
  "XL Energy Drink",
  "XO Energy Drink",
  "Xo2 Uplift Soda",
  "XS Energy Drink",
  "Xtazy Energy Drink",
  "Xtreme Shock Energy Drink",
  "Xyience Xenergy Energy Drink",
  "Y.E.S. Energy Shot",
  "Yellow Tea",
  "Yerba Mate Tea",
  "Yoo-Hoo Chocolate Drink",
  "Zest Highly Caffeinated Tea",
  "Zevia Cola",
  "ZipFizz Energy Drink",
  "ZizZazz Energy Drink",
  "Zola Coconut Water Espresso",
  "Zombie Blood Energy Potion",
  "ZUM XR Energy Drink",
];

function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
              b.addEventListener("click", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
      x[i].parentNode.removeChild(x[i]);
    }
  }
}
/*execute a function when someone clicks in the document:*/
document.addEventListener("click", function (e) {
    closeAllLists(e.target);
});
}

autocomplete(document.getElementById("myInput"), caffeine_drinks);
